### ISSUE TITLE
College, Zone, Rpc, State and User make text field in search filter

### ISSUE THREAD

**Issue by vibhavsathe** [webaccess/medha-STPC#91]
Filters should be able to search data even if we add similar letters for eg: in state even if we type "mah" in filter it should search for states starting with mah i.e maharashtra.

**Comment by yogesh-dalvi** [comment]
@mayanksurti 
**1)  **Issue#1****
![state-error](https://user-images.githubusercontent.com/42199573/77311767-c0db3e00-6d26-11ea-9b53-d79d1ebc811b.PNG)

 Steps to reproduce the issue:-

1.  In the search filter, enter a non-matching data for eg :- Suppose state table is having only one state i.e Uttar Pradesh and then we enter any non -matching random data i.e "ua"
2. Click on search. You will not get any result 
3.  Then click back space to clear the text box. 
4. After clicking backspace and cleaing data this error is produced.


**2) Issue#2**

Follow the same steps as above. When there is no data instead of showing spinner, "No data found" text can be shown in "Manage State" screen  as shown in all other manage screens

**3) Issue#3**
No text filter added in Manage College screen
